@HostAddress = http://localhost:5130

### Zapnutí časovače pro Genshin
POST {{HostAddress}}/GenshinTracker/start
Accept: application/json
X-API-Key: ahoj

### Vypnutí časovače
POST {{HostAddress}}/GenshinTracker/stop
Accept: application/json
X-API-Key: ahoj

### Získání aktuálního stavu časovače
GET {{HostAddress}}/GenshinTracker/status
Accept: application/json
X-API-Key: ahoj